#!/bin/bash

cd $HOME/Projects && ls -la

. ~/.extra-paths.sh
. ~/.environment_variables.sh
. ~/.secret_environment_variables.sh


for path in "${ENV_PATHS[@]}"
do
  export PATH="${path}:{$PATH}"
done

for SCRIPT in ~/Projects/Personal/dotfiles/autorun/*
do
  source $SCRIPT
done

eval "$(rbenv init -)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
