set nocompatible
filetype off

" Plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()
	Plugin 'VundleVim/Vundle.vim'
	Plugin 'scrooloose/nerdtree.git'
	Plugin 'flazz/vim-colorschemes'
	Plugin 'junegunn/fzf'
	Plugin 'junegunn/fzf.vim'
	Plugin 'tpope/vim-fugitive'
	Plugin 'airblade/vim-gitgutter'
" End of Plugins

" Terminal Configs
	" Disable annoying bell sound
	set noerrorbells visualbell t_vb=
	if has('autocmd')
  	autocmd GUIEnter * set visualbell t_vb=
	endif
" End of Terminal Configs

" NerdTree Configs
let g:NERDTreeWinPos = "right" 

" Fzf Configs
	" Init
	set rtp+=~/.fzf

	" Bindings
	map <C-p> :Files<cr>
	nmap <C-p> :Files<cr>
	nmap <Leader>c :Commits<cr>
	
	" Visuals and Behaviour
	let g:fzf_action = {
  	\ 'ctrl-t': 'tab split',
  	\ 'ctrl-x': 'split',
  	\ 'ctrl-v': 'vsplit' }

	" Default fzf layout
	" - down / up / left / right
	let g:fzf_layout = { 'down': '~40%' }

	" In Neovim, you can set up fzf window using a Vim command
	let g:fzf_layout = { 'window': 'enew' }
	let g:fzf_layout = { 'window': '-tabnew' }

	" Customize fzf colors to match your color scheme
	let g:fzf_colors =
	\ { 'fg':      ['fg', 'Normal'],
  	\ 'bg':      ['bg', 'Normal'],
  	\ 'hl':      ['fg', 'Comment'],
  	\ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  	\ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  	\ 'hl+':     ['fg', 'Statement'],
  	\ 'info':    ['fg', 'PreProc'],
  	\ 'prompt':  ['fg', 'Conditional'],
  	\ 'pointer': ['fg', 'Exception'],
  	\ 'marker':  ['fg', 'Keyword'],
  	\ 'spinner': ['fg', 'Label'],
  	\ 'header':  ['fg', 'Comment'] }

	let g:fzf_history_dir = '~/.local/share/fzf-history'
" END of Fzf Config

" Syntax and Style
set tabstop=2
set number
set go-=L " Removes left hand scroll bar 

syntax on
colorscheme Monokai 

let b:surround_{char2nr('-')} = "<% \r %>" " displays <% %> correctly 
set cpoptions+=$ " puts a $ marker for the end of words/lines in cw/c$ commands

filetype plugin on
