. ~/.environment_variables.sh
. ~/.secret_environment_variables.sh


# ZSH Configs
	export ZSH="$HOME/.oh-my-zsh"
	
	ZSH_THEME="steeef"
	HISTFILE=~/.zsh_history
	
	plugins=(git)
	source $ZSH/oh-my-zsh.sh
# End of ZSH Config

# NVM Config
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# End of NVM Config

# Rbenv Config
	# eval "$(rbenv init - --no-rehash)"
# End of Rbenv Config

# Load all scripts in autorun folder
	for SCRIPT in ~/Projects/Dotfiles/autorun/*
	do
  	source $SCRIPT
	done
# End of autoscripts

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
cd $HOME/Projects && ls -la
