# $DOTFILES_PATH is an environment variable 

. ~/.environment_variables.sh
. ~/.secret_environment_variables.sh

# ZSH Configs
	export ZSH="$HOME/.oh-my-zsh"
	
	ZSH_THEME="steeef"
	HISTFILE=~/.zsh_history
	
	plugins=(git)
	source $ZSH/oh-my-zsh.sh
# End of ZSH Config

# Rbenv Config
	# eval "$(rbenv init - --no-rehash)"
# End of Rbenv Config

# Load all scripts in autorun folder
	for SCRIPT in $DOTFILES_PATH/autorun/*
	do
  	source $SCRIPT
	done
# End of autoscripts

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
cd $HOME/Projects && ls -la
