# Path Updates
	export PATH="~/.bin:$PATH"
	export PATH="~/.rbenv/bin:$PATH"
	export PATH="~/./node_modules/.bin:$PATH"
	export PATH="/usr/local/sbin:$PATH"
	export PATH="$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin"
	# End of Path Updates

# ZSH Configs
	export ZSH="$HOME/.oh-my-zsh"
	
	ZSH_THEME="steeef"
	HISTFILE=~/.zsh_history
	
	plugins=(git)
	source $ZSH/oh-my-zsh.sh
# End of ZSH Config

# NVM Config
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# End of NVM Config

# Rbenv Config
	# eval "$(rbenv init - --no-rehash)"
# End of Rbenv Config

# Load all scripts in autorun folder
	for SCRIPT in ~/Projects/Dotfiles/autorun/*
	do
  	source $SCRIPT
	done
# End of autoscripts

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
. ~/.environment_variables.sh
cd $HOME/Projects && ls -la
